### ISSUE TITLE
Is it possible to provide results of entity linking?

### ISSUE THREAD

**Issue by yhshu** [salesforce/rng-kbqa#1]
RnG-KBQA's entity linking are a further enhancement to GrailQA implementation.
Currently, entity linking is a relatively independent step, and significantly improving the effectiveness of entity linking is usually difficult.
Would the authors be willing to publish the results of entity linking?

This may be of great help for subsequent studies. 
Many thanks.

**Comment by xiye17** [comment]
Sure. I am out of town now and will get back to you soon after I return.

**Comment by xiye17** [comment]
Would you mind shooting me an email at xiye@cs.utexas.edu.
