### ISSUE TITLE
version of transformers

### ISSUE THREAD

**Issue by yeliu918** [salesforce/rng-kbqa#10]
Hi Xi, 

Thanks for open-source this awesome work! 
May I know what's the version you install for `transformers`? I saw `pytorch-transformers==1.1.0` in requirements.txt but I have a package missing problem when `importing transformers` in run_ranker.py and run_generator.py. I tried `transformers==3.4.0` and `transformers==4.16.0` but they all have some problems.

**Comment by xiye17** [comment]
Try Transformers 3.3.1 as in the main readme.
PyTorch-transformers is a different thing (used for some dependency) Sorry for the confusion.

**Comment by yeliu918** [comment]
Thanks, it works well!
