### ISSUE TITLE
other dataset

### ISSUE THREAD

**Issue by JBoRu** [salesforce/rng-kbqa#11]
Hi,
    Congratulations on such interesting work. Existed research work always considered the CWQ and WebQSP datasets. However, you only test the WebQSP in your paper. I want to know: (1) if you have conducted the experiment on CWQ to verify your method performance; (2) if not, how to conduct the experiment on this new dataset? I think it is should similar to the WebQSP. Looking forward to your reply.

**Comment by xiye17** [comment]
(1) No. I didn't try that. 
(2) I just took a quick look at CWQ. Yeah it looks like WebQSP. So the procedure should be similar. Here are some troubles I can provision: 
a. There's no s-exprs for sparql queries in CWQ. I guess my code can parse some of them but surely not all. It could take time to handle some corner cases.
b. CWQ has some 4-hop paths starting from one node, our current enumeration doesn't cover those. If we do there will be way too many candidates. So the enumeration coverage might not be very well in order for the generator to work well.

My impression is CWQ is a dataset designed for handling mostly *in-domain but very long* sparql queries. Cased-Based Methods (CBR) should be more appropriate (and better) for this dataset as it has enough support from in-domain data points.

**Comment by JBoRu** [comment]
Thanks for your reply. I will try it.
