### ISSUE TITLE
Question about knowledge base

### ISSUE THREAD

**Issue by PlusRoss** [salesforce/rng-kbqa#12]
Hi!

Great work! May I know what knowledge base are you using for this paper? Freebase? But ELQ is based on Wikidata right?

**Comment by xiye17** [comment]
yes. We are using Freebase.
ELQ predicts entity id based on wikidata. I used an API to convert that to entity id of Freebase.

**Comment by PlusRoss** [comment]
I see. Thanks for your answer!
