### ISSUE TITLE
How to process the mids which can't convert to string name?

### ISSUE THREAD

**Issue by JBoRu** [salesforce/rng-kbqa#14]
Hi,
   When I follow this excellent work, I encounter some problems: I can't convert some mids to the string type name. I use your get_name script and get some triples output. But there is not any helpful string name information. How should I process this problem? Thanks!

---------------------------------
Here are some example of mids and their one-hop triples by executed search on the freebase:

**m.0gxnnwp :**  `[['m.0gxnnwp', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'people.sibling_relationship'], ['m.0gxnnwp', 'type.object.type', 'people.sibling_relationship'], ['m.0gxnnwp', 'people.sibling_relationship.sibling', 'm.06w2sn5'], ['m.0gxnnwp', 'people.sibling_relationship.sibling', 'm.0gxnnwq']]`
**m.0855mj_** :  `[['m.0855mj_', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'film.performance'], ['m.0855mj_', 'type.object.type', 'film.performance'], ['m.0855mj_', 'film.performance.actor', 'm.09l3p'], ['m.0855mj_', 'film.performance.film', 'm.062zjtt'], ['m.0855mj_', 'film.performance.character', 'm.0dttll']]`
**m.04g55p8:** `[['m.04g55p8', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'common.topic'], ['m.04g55p8', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'user.dfhuynh.default_domain.assassination'], ['m.04g55p8', 'type.object.type', 'common.topic'], ['m.04g55p8', 'type.object.type', 'user.dfhuynh.default_domain.assassination'], ['m.04g55p8', 'user.dfhuynh.default_domain.assassination.assassinated_person', 'm.0d3k14'], ['m.04g55p8', 'user.dfhuynh.default_domain.assassination.assassin', 'm.0bgl08'], ['m.04g55p8', 'user.dfhuynh.default_domain.assassination.date', '1960-12-11-08:00'], ['m.04g55p8', 'user.dfhuynh.default_domain.assassination.location', 'm.0rqf1'], ['m.04g55p8', 'user.dfhuynh.default_domain.assassination.method', 'm.04g56gm'], ['m.04g55p8', 'user.dfhuynh.default_domain.assassination.outcome', 'm.04g5679']]`

**Comment by xiye17** [comment]
Sure. Could you elaborate a bit? What's the get_name script, and what you wanna get from the mid (and/or you wanna use them for)? Thanks!

**Comment by JBoRu** [comment]
Hi,
   First, the get_name script reference to https://github.com/salesforce/rng-kbqa/blob/80d56b5702255e84a7624cc0184d89dbf42ee83d/framework/executor/sparql_executor.py#L146
   Second, the reason I want to get the mid's name is that I want to instantiate these mid entities and input them to PLMs. Because it seems difficult for PLM to understand the mid representation(eg. m.0gxnnwp).

**Comment by xiye17** [comment]
This could happen when there are no object name for these entities.

I don’t have good solutions as well. If there are only a small fraction of this kind of data points, I’ll probably just ignore them (filtering) or use [object type] as a general semantic placeholder. There are inevitably noise in the knowledge base.

**Comment by JBoRu** [comment]
OK, Thanks for your help!
