### ISSUE TITLE
Question about WebQSP evaluation

### ISSUE THREAD

**Issue by PlusRoss** [salesforce/rng-kbqa#15]
Hi!

The WebQSP eval.py file will generate 2 F1 scores: "Average f1 over questions (accuracy)" and "F1 of average recall and average precision". May I know which one are you showing?

Thanks.

**Comment by xiye17** [comment]
Average f1 over questions (accuracy) is the metrics reported in the paper.

F1 of average recall and precision is the F1 of the averaged recall over all questions and the averaged precision over all the questions.

**Comment by PlusRoss** [comment]
I see. Thanks for your reply!

**Comment by PlusRoss** [comment]
Sorry I have a follow-up question: I use the [parse_sparql.py](https://github.com/salesforce/rng-kbqa/blob/main/WebQSP/parse_sparql.py) file to process WebQSP data and find that the ground-truth s-expressions can only get about 90% F1 on the test data. Is this the same in your case? If not, could me provide me the processed WebQSP.*.expr.json files?

**Comment by xiye17** [comment]
I didn't test but it should be fine. Not all sparql query can be parsed in my code. I can also send WebQSP.*.expr.json to you for checking. Just shot me an email.
