### ISSUE TITLE
About knowledge graph

### ISSUE THREAD

**Issue by thchau0** [salesforce/rng-kbqa#17]
Hi, 
Can you suggest how I can implement this KBQA model on my own knowledge graph dataset?
I have tried to load the RDF file into the virtuoso server directly, but the model seems not to detect the graph.
Do I need to do any configuration on my RDF file?
Or is it the problem related to entity linking? If so, what can I do to make the KBQA model work on my knowledge graph dataset?

**Comment by xiye17** [comment]
Hi,

I am not an expert of KB so I have only set up the KB using the repo shared by GrailQA. Nevertheless, here are some suggestions.

1. Test whether the KB is set up correctly. Try using the API (e.g., get_label  in sparql_executor) in to see if you can get the label/relations for a node id.
2. Test entity linking, see if you can detect the entity mentions and link that to your customized nodes. I think the current entity linker only knows how to map mentions to nodes in Freebase. So there might be some work here.
3. If step 1 and 2 work, you can try use the pretrained ranker and generator model for running inference. At least ranker should work.
4. Adapt the models for your own database.

Hope this could help.
