### ISSUE TITLE
Something wrong with reproduction

### ISSUE THREAD

**Issue by dongguanting** [salesforce/rng-kbqa#18]
when I use walk_through_demo.sh, it will stuck at entity disambiguating. I do not know what is going wrong, which seems can not read examples:
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/60767110/192446799-e2d9b046-65f3-4a36-805c-1b34b2a95bb6.png">
 
could you help me @xiye17 ? thx!

**Comment by czh17** [comment]
我遇到了相同的问题，请问您最后解决了吗？
