### ISSUE TITLE
the file in ontology

### ISSUE THREAD

**Issue by LLLLLLoki** [salesforce/rng-kbqa#2]
Thank you very much for your code sharing, I don't quite understand what these files in ontology mean?
domain_dict, domain_info ,fb_roles ,fb_types ,full_reverse_properties.json ,reverse_properties do they have any connection with FBbase?

**Comment by xiye17** [comment]
They are dicts of the tyles and relations of the knowledge base, taken from GrailQA repo. You may find more descriptions there.
