### ISSUE TITLE
Training of Mention Detection Model (BERT-NER)

### ISSUE THREAD

**Issue by gourango01** [salesforce/rng-kbqa#20]
I would like to train the "mention detection model" on the GrailQA dataset, which can be done using /GrailQA/entity_linker/BERT_NER/run_ner.py. But it also expects GrailQA dataset in CoNLL-2003 format (i.e., question tokens tagged with  ["B", "I", "O", "[CLS]", "[SEP]"] tags) which is not present in the repository.
So would you please share the processed GrailQA dataset (train and valid split) or script for converting the dataset into the required format?
Can you please confirm that the BERT-NER model has been trained with the parameters mentioned in /GrailQA/entity_linker/BERT_NER/run_ner.py ?

**Comment by xiye17** [comment]
I didn't train this ner model. As mentioned in the README, the NER system is taken  from [Original GrailQA](https://github.com/dki-lab/GrailQA) Code Repo. You might want contact them for this.
