### ISSUE TITLE
How long does enumerate candidates need?

### ISSUE THREAD

**Issue by HaishuoFang** [salesforce/rng-kbqa#21]
Hello,

I was wondering how long it will take to get the candidates for train data? I have been running it for 4 hours on a single cpu. If i understand it correctly, the most time-consuming part is edit distance part. Would you like to provide the results for training. Thanks in advance!

Best,
Haishuo

**Comment by xiye17** [comment]
It should be able to be finished in one or two days if you use the KB cache.

**Comment by HaishuoFang** [comment]
Thanks!
