### ISSUE TITLE
Is there any release for query enumeration and ranking results?

### ISSUE THREAD

**Issue by yhshu** [salesforce/rng-kbqa#3]
Hi there, 
I'm currently interested in reproducing the results of RnG-KBQA.
Dev set is relatively small. 
It workedfine for me.
However, training set might be too big for enumerating candidates, maybe even a few days for this single step?
I wonder is there a way to share files for the enumeration of candidate queries in training set, and maybe the ranking results?

Thanks a lot.

**Comment by xiye17** [comment]
Hi I'll have to take a look at what I have. I am not 100% sure I have that file somewhere. (It was stored on Salesforce space which might be released after my internship terminates).

At the same time maybe you can try to breakdown the training set into several chunks and manually parallelize it. It could be good if you also keep it running in back-end if I am not able to find it. In my impression it takes roughly a day or so if you use the cache. I am not sure though.

**Comment by yhshu** [comment]
Thanks for your instant reply and support.

**Comment by yhshu** [comment]
Thanks, I rechecked my cache and it was indeed placed under the wrong path by my fault. 
The use of the cache is sufficient to support the efficiency.
I won't bother you to find the relevant documents, thanks again.
