### ISSUE TITLE
Is it possible that you share the final Logical Form generated by our method on Webqsp dataset

### ISSUE THREAD

**Issue by lihuiliullh** [salesforce/rng-kbqa#8]
Hi, I try to run the algorithm according to the readme, but I failed several times. 
Is it possible that you share the final Logical Form generated by our method on Webqsp dataset?
If you could share other files, that would be even better. @xiye17

**Comment by xiye17** [comment]
sure I can find that for you. Just shoot me an email at xiye@cs.utexas.edu
